---
name: "Code Quality: Terraform"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Run `terraform fmt`
        run: terraform fmt -check

      - name: Run `terraform init`
        id: init
        run: terraform init

      - name: Run `terraform validate`
        run: terraform validate -no-color
